title: Opionated DS and ML 
author:
  name: DemirTonchev
  
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Stuff to read when bored. 

# Build settings

#theme: minima
remote_theme: jekyll/minima

show_excerpts: true

header_pages:
  - about.md
  
plugins:
  - jekyll-seo-tag

future: true

excerpt_separator: <!--more-->

social_links:
  - { platform: github,         user_url: "https://github.com/DemirTonchev" }
#  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
