title: Opionated DS and ML 
author:
  name: DemirTonchev
  
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Stuff to read when bored. 

# Build settings

#theme: minima
remote_theme: jekyll/minima

show_excerpts: true

header_pages:
  - about.md
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
